iota-uz/iota-sdk

- modules/core/infrastructure/persistence/core_mappers.go
- modules/core/infrastructure/persistence/permission_repository.go
- modules/core/infrastructure/persistence/role_repository.go
- modules/core/seed/seed_user.go
I think setting user id on your own messes with auto_increment of postgres. It should be set by postgres to keep it in sync, otherwise you can't insert next user.
> role, permission repo fixes, fix user seed

- go.mod
- modules/core/infrastructure/persistence/user_repository.go
- use the correct param number in userUpdateLastLoginQuery
- update the makefile commands for localdb to detatch after running the container
- update the tailwind commands to use npx (remove the hassle of installing tailwind and adding it to path)
> fix: use the correct param number in userUpdateLastLoginQuery

- pkg/application/application.go
This PR fixes #59 
Updated to use the filepath.WalkDir feature introduced in Go 1.16 (See details [here](https://pkg.go.dev/path/filepath#WalkDir)).
I did conduct minimal testing of this on a Windows device and additional testing on a Mac with no issues identified.
Happy to discuss anything I may have missed as I believe we use the embedded file system for more than just localization. 
Thanks.
> use `filepath.WalkDir` to provide os agnostic file scans

- pkg/composables/request.go
https://github.com/iota-uz/iota-sdk/issues/97
> eliminate possibility of pageCtx being nil

- .env.example
- .github/workflows/test.yml
- e2e/cypress.config.js
- e2e/cypress/e2e/users/register.cy.js
- modules/core/presentation/locales/en.json
- modules/core/presentation/locales/ru.json
- modules/core/presentation/locales/uz.json
- modules/core/presentation/templates/layouts/base.templ
- modules/core/presentation/templates/layouts/base_templ.go
- modules/core/presentation/templates/pages/users/new.templ
- modules/core/presentation/templates/pages/users/new_templ.go
- modules/core/presentation/templates/pages/users/shared.templ
- modules/core/presentation/templates/pages/users/shared_templ.go
- modules/crm/infrastructure/persistence/schema/crm-schema.sql
> [!NOTE]  
> - I removed `defer async` from htmx loading tags because it is leading to race conditions: the preload module of htmx is being loaded earlier than htmx itself which is leading to broken frontend and inconsistent e2e test runs.
> - Added missing localization entries and removed redundant form attributes
Closes: https://github.com/iota-uz/iota-sdk/issues/106
> Basic e2e flow with cypress.js

- modules/core/presentation/templates/pages/users/edit.templ
> fix: delete user modal button texts

- modules/core/presentation/templates/pages/users/edit_templ.go
- pkg/schema/diff/generator.go
> fix: sync changes of generator.go with latest changes

- modules/core/domain/aggregates/role/role_repository.go
- modules/core/domain/aggregates/user/user_repository.go
- modules/core/domain/entities/currency/currency_repository.go
- modules/core/domain/entities/permission/permission_repository.go
- modules/core/domain/entities/session/session_repository.go
- modules/core/domain/entities/upload/upload_repository.go
- modules/core/infrastructure/persistence/currency_repository.go
- modules/core/infrastructure/persistence/permission_repository.go
- modules/core/infrastructure/persistence/role_repository.go
- modules/core/infrastructure/persistence/session_repository.go
- modules/core/infrastructure/persistence/upload_repository.go
- modules/core/infrastructure/persistence/user_repository.go
- modules/core/interfaces/graph/generated.go
- modules/core/interfaces/graph/users.graphql
- modules/core/interfaces/graph/users.resolvers.go
- modules/core/presentation/controllers/user_controller.go
Second iteration of #143 but without hrm and warehouse modules.
> add: `SortBy` for core modules

- modules/core/presentation/locales/en.json
- modules/core/presentation/locales/ru.json
- modules/core/presentation/locales/uz.json
- modules/core/presentation/templates/pages/roles/roles.templ
- modules/core/presentation/templates/pages/roles/roles_templ.go
- modules/core/presentation/templates/pages/users/users.templ
- modules/core/presentation/templates/pages/users/users_templ.go
> fix: hard-coded yesterday/ereyesterday filter values

- modules/core/domain/aggregates/user/user_dto.go
> fix: MiddleName in user made optional

- modules/core/presentation/controllers/roles_controller.go
> fix: sort permission groups to avoid arbitrary ordering

- migrations/changes-1741852019.sql
- modules/core/domain/entities/passport/passport.go
- modules/core/infrastructure/persistence/schema/core-schema.sql
- modules/crm/domain/aggregates/client/client_dto.go
> fix: update instead of insert on client edit

- modules/hrm/infrastructure/persistence/employee_repository.go
- modules/hrm/presentation/mappers/mappers.go
- modules/hrm/presentation/templates/pages/employees/edit.templ
- modules/hrm/presentation/templates/pages/employees/edit_templ.go
- modules/hrm/presentation/templates/pages/employees/employees.templ
- modules/hrm/presentation/templates/pages/employees/employees_templ.go
- modules/hrm/presentation/templates/pages/employees/new.templ
- modules/hrm/presentation/templates/pages/employees/new_templ.go
- modules/hrm/presentation/templates/pages/employees/shared.templ
- modules/hrm/presentation/templates/pages/employees/shared_templ.go
> fix: employee urls and left out form fields

- modules/core/presentation/locales/en.json
- modules/core/presentation/locales/ru.json
- modules/core/presentation/locales/uz.json
- modules/hrm/domain/aggregates/employee/employee_create_dto.go
- modules/hrm/domain/aggregates/employee/employee_update_dto.go
- modules/hrm/presentation/controllers/employee_controller.go
- modules/hrm/presentation/locales/en.toml
- modules/hrm/presentation/locales/ru.toml
- modules/hrm/presentation/locales/uz.toml
- modules/hrm/presentation/templates/pages/employees/shared.templ
- modules/hrm/presentation/templates/pages/employees/shared_templ.go
- pkg/serrors/base.go
- pkg/serrors/validation.go
> fix: show error messages on invalid PIN/TIN and etc

- migrations/changes-1740741698.sql
- migrations/changes-1742917178.sql
- modules/crm/domain/aggregates/client/client.go
- modules/crm/domain/aggregates/client/client_dto.go
- modules/crm/infrastructure/persistence/client_repository_test.go
- modules/crm/infrastructure/persistence/crm_mappers.go
- modules/crm/infrastructure/persistence/schema/crm-schema.sql
Since phone number is no longer required, I removed it from client constructor and added WithPhone option
> don't require phone number in client constructor

- pkg/schema/collector/tree_builder.go
- pkg/schema/collector/tree_builder_test.go
Description:
Fixes matching columns in table in findColumnIndex
Fixes #246
> Fix bug in findColumnIndex and use normalized column names during matching

- components/base/input/switch.templ
- components/base/input/switch_templ.go
closes: https://github.com/iota-uz/iota-sdk/issues/263
> minor style fix

- modules/core/presentation/controllers/login_controller.go
> fix: user not found exception msg

- Makefile
- modules/finance/presentation/templates/pages/moneyaccounts/edit.templ
- modules/finance/presentation/templates/pages/moneyaccounts/edit_templ.go
- modules/finance/presentation/templates/pages/moneyaccounts/new.templ
- modules/finance/presentation/templates/pages/moneyaccounts/new_templ.go
> fix: floating point values in the amount field of the finance module -> account in the create/edit actions

- modules/core/presentation/templates/pages/groups/edit.templ
- modules/core/presentation/templates/pages/groups/edit_templ.go
- modules/core/presentation/templates/pages/groups/new.templ
- modules/core/presentation/templates/pages/groups/new_templ.go
- modules/core/presentation/templates/pages/groups/shared.templ
- modules/core/presentation/templates/pages/groups/shared_templ.go
> fix: fix id collision in checkboxes in groups

- CLAUDE.md
- Makefile
- modules/finance/presentation/controllers/counterparties_controller.go
- modules/finance/presentation/controllers/counterparties_controller_test.go
- modules/finance/presentation/controllers/dtos/counterparty_dto.go
- modules/finance/presentation/mappers/mappers.go
- modules/finance/presentation/viewmodels/enums.go
- Fix TIN field value preservation on counterparty form validation errors
- Add comprehensive TDD tests for TIN field preservation functionality
- Enhance fmt make target to include template generation for better development workflow
- Improve build process consistency by automatically regenerating templates
**Regression areas that could break:**
- Counterparty form validation and error handling
- Template rendering after form validation errors
- Build process and template generation pipeline
- Form field value preservation across validation cycles
**Edge cases to verify:**
- TIN field clearing when form validation fails with multiple errors
- Template regeneration during development workflow
- Form state preservation with invalid TIN formats
- Concurrent form submissions with validation …
> fix: preserve TIN field value and enhance build process
